### ISSUE TITLE
Zombie process

### ISSUE THREAD

**Issue by gniting** [ido1990/tailscale-relay#4]
Running this container results in a zombie process on the host:
`root        3026  0.0  0.0      0     0 ?        Z    16:42   0:00 [tailscale] <defunct>`

Here's the `docker run` command that I used:
```
docker run -d \                                                                                                       
        -v /tailscale \
        --cap-add=NET_ADMIN \
        --network=<my_docker_network_name> \
        -e "ROUTES=list_of_local_subnets_in_192.168.x.x_format" \
        -e "AUTHKEY=xxxxxxxxxxxxxx" \
        ido1990/tailscale-docker:latest
```

Interestingly, tailscale seems to be functional.

**Comment by gniting** [comment]
Potentially this helps to fix?
https://worp.io/docker-and-zombie-processes-pid-1-in-containers/

**Comment by ido1990** [comment]
Thank you for the fix!
I just read the notes on the repository of **tini** and saw this one:
`NOTE: If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just [pass the --init flag to docker run](https://docs.docker.com/engine/reference/commandline/run/).`

Did you know that it's already included?

**Comment by ido1990** [comment]
@gniting 
BTW, I had to change the way you implemented the **tini**.
It's different in Alpine and the way you did it, broke the image when tested.

**Comment by gniting** [comment]
> Did you know that it's already included?

I did not unfortunately. Glad that you found an alternative fix.
